name: Owasp dependency Security Check
on: [push, pull_request]
jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: Owasp dependency vulnerability test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build project with Maven
        run: mvn clean install

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'vulnerability test'
          path: '.'
          format: 'XML,HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

      - name: Report dependency vulnerability test results
        uses: gmazzo/publish-report-annotations@v1
        if: always()
        with:
            checkName: "Dependency Vulnerability Report (omitting passed)"
            reports: |
              reports/dependency-check-report.xml
            testsSummary: full
            filterPassedTests: true
            detectFlakyTests: true
